In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('./Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
# risk dictionary
risk = {
    "low_risk": 0,
    "high_risk":1
}
# Months' names encoded using the dictionary values
df["loan_status"] = df["loan_status"].apply(lambda x: risk[x])
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,0,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,0,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,0,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,0,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,0,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = df.copy()
#columns1 = ["application_type",'initial_list_status','pymnt_plan','loan_status','verification_status','home_ownership']
df2['application_type'] = le.fit_transform(df2['application_type'])
df2['initial_list_status'] = le.fit_transform(df2['initial_list_status']) 
df2['pymnt_plan'] = le.fit_transform(df2['pymnt_plan']) 
df2['verification_status'] = le.fit_transform(df2['verification_status'])
df2['home_ownership'] = le.fit_transform(df2['home_ownership'])
df2['hardship_flag'] = le.fit_transform(df2['hardship_flag'])
df2['debt_settlement_flag'] = le.fit_transform(df2['debt_settlement_flag'])
df2.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,3,66000.0,1,Mar-2019,0,0,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,0,0
1,25000.0,0.2000,929.09,1,105000.0,2,Mar-2019,0,0,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,0,0
2,20000.0,0.2000,529.88,1,56000.0,2,Mar-2019,0,0,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,0,0
3,10000.0,0.1640,353.55,3,92000.0,2,Mar-2019,0,0,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,0,0
4,22000.0,0.1474,520.39,1,52000.0,0,Mar-2019,0,0,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,0,0

In [8]:
columns2 = ['next_pymnt_d','issue_d']
loan_df = df2.drop(columns=columns2)

# Split the Data into Training and Testing

In [9]:
# Create our features
X =loan_df.drop(columns ='loan_status')

# Create our target
y = loan_df['loan_status']

In [10]:
X.describe()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
count,68817.000000,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.0,6.881700e+04,6.881700e+04,68817.000000,6.881700e+04,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,1.812779,8.821371e+04,0.669994,0.0,21.778153,0.217766,0.497697,...,95.057627,30.626217,0.125972,0.0,2.100332e+05,6.133843e+04,29734.128558,5.572240e+04,0.0,0.0
std,10277.348590,0.048130,288.062432,0.941313,1.155800e+05,0.719105,0.0,20.199244,0.718367,0.758122,...,8.326426,33.631463,0.336732,0.0,1.928088e+05,5.738798e+04,26795.394232,5.095845e+04,0.0,0.0
min,1000.000000,0.060000,30.890000,0.000000,4.000000e+01,0.000000,0.0,0.000000,0.000000,0.000000,...,20.000000,0.000000,0.000000,0.0,3.600000e+03,2.350000e+02,100.000000,1.270000e+02,0.0,0.0
25%,9000.000000,0.088100,265.730000,1.000000,5.000000e+04,0.000000,0.0,13.890000,0.000000,0.000000,...,93.000000,0.000000,0.000000,0.0,6.697700e+04,2.650300e+04,11600.000000,2.288000e+04,0.0,0.0
50%,15000.000000,0.118000,404.560000,1.000000,7.300000e+04,1.000000,0.0,19.760000,0.000000,0.000000,...,100.000000,20.000000,0.000000,0.0,1.467100e+05,4.535700e+04,22100.000000,4.200000e+04,0.0,0.0
75%,24000.000000,0.155700,648.100000,3.000000,1.040000e+05,1.000000,0.0,26.660000,0.000000,1.000000,...,100.000000,50.000000,0.000000,0.0,3.036400e+05,7.657000e+04,39300.000000,7.249900e+04,0.0,0.0
max,40000.000000,0.308400,1676.230000,3.000000,8.797500e+06,2.000000,0.0,999.000000,18.000000,5.000000,...,100.000000,100.000000,4.000000,0.0,3.292782e+06,1.295455e+06,509400.000000,1.426964e+06,0.0,0.0

In [11]:
# Normal train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({0: 51366, 1: 246})

In [12]:
# Check the balance of our target values
y

0        0
1        0
2        0
3        0
4        0
        ..
68812    0
68813    0
68814    0
68815    0
68816    0
Name: loan_status, Length: 68817, dtype: int64

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [13]:
from sklearn.preprocessing import StandardScaler
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
# Resample the training data with the RandomOversampler
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(bootstrap=True, class_weight=None,
                criterion='gini', max_depth=None, max_features='auto',
                max_leaf_nodes=None, min_impurity_decrease=0.0,
                min_samples_leaf=2, min_samples_split=2,
                min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
                oob_score=False, random_state=1, replacement=False,
                sampling_strategy='auto', verbose=0, warm_start=False)
brf.fit(X_train_scaled, y_train)

BalancedRandomForestClassifier(min_samples_leaf=2, n_jobs=1, random_state=1)

In [15]:
# Calculated the balanced accuracy score
y_pred = brf.predict(X_test_scaled)

print("Balanced Accuracy Score :",balanced_accuracy_score(y_test, y_pred))

Balanced Accuracy Score : 0.7077714436551232

In [16]:
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0        14220         2884
Actual 1           42           59

In [17]:
# Print the imbalanced classification report
#0 : low_risk, #1:high risk
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))
#    "low_risk": 0,
#    "high_risk":1

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.83      0.58      0.91      0.70      0.50     17104
          1       0.02      0.58      0.83      0.04      0.70      0.47       101

avg / total       0.99      0.83      0.59      0.90      0.70      0.50     17205

In [18]:
# We can sort the features by their importance.
sorted(zip(brf.feature_importances_, X.columns), reverse=True)

[(0.08656635716268982, 'last_pymnt_amnt'),
 (0.06712830386036822, 'total_rec_prncp'),
 (0.06455572411377343, 'total_rec_int'),
 (0.057853975663494615, 'total_pymnt_inv'),
 (0.048210348259077704, 'total_pymnt'),
 (0.03736431527713882, 'int_rate'),
 (0.02006311966510871, 'dti'),
 (0.018243744205644088, 'max_bal_bc'),
 (0.01777158070527311, 'mths_since_rcnt_il'),
 (0.01764144706176067, 'installment'),
 (0.01690054576124317, 'bc_util'),
 (0.016480707633865468, 'out_prncp'),
 (0.016306097838661035, 'revol_bal'),
 (0.016121986006466128, 'total_bal_il'),
 (0.01593538089023328, 'annual_inc'),
 (0.01563299490771933, 'avg_cur_bal'),
 (0.0152869642224296, 'total_bal_ex_mort'),
 (0.015241056250555341, 'mo_sin_old_rev_tl_op'),
 (0.015123807507525074, 'il_util'),
 (0.015013270864131251, 'mo_sin_old_il_acct'),
 (0.014945486335673972, 'total_rev_hi_lim'),
 (0.01484065643494162, 'mths_since_recent_inq'),
 (0.014340190007263852, 'total_il_high_credit_limit'),
 (0.014292475835458712, 'out_prncp_inv'),
 (0.01415276313592502, 'mths_since_recent_bc'),
 (0.013732616158397824, 'tot_cur_bal'),
 (0.013516795695660961, 'all_util'),
 (0.01251211634001406, 'num_il_tl'),
 (0.011986361349326376, 'total_bc_limit'),
 (0.011908663325022453, 'total_acc'),
 (0.011899157708679924, 'tot_hi_cred_lim'),
 (0.011747325231852375, 'loan_amnt'),
 (0.011358711737535214, 'num_bc_tl'),
 (0.011269869753550465, 'bc_open_to_buy'),
 (0.010788301400940432, 'inq_last_12m'),
 (0.010526669920608274, 'open_acc'),
 (0.010299574699024186, 'mo_sin_rcnt_tl'),
 (0.009832247283166484, 'num_sats'),
 (0.009801999364420324, 'open_acc_6m'),
 (0.009743966353985648, 'open_il_24m'),
 (0.00928695390022045, 'num_rev_accts'),
 (0.008855692151432792, 'mo_sin_rcnt_rev_tl_op'),
 (0.00864482554275774, 'num_op_rev_tl'),
 (0.008325129026127035, 'inq_fi'),
 (0.008293938878766702, 'pct_tl_nvr_dlq'),
 (0.008264930610374723, 'total_rec_late_fee'),
 (0.00819806964158279, 'acc_open_past_24mths'),
 (0.007706894134338586, 'num_rev_tl_bal_gt_0'),
 (0.007633282740134653, 'num_tl_op_past_12m'),
 (0.0075843868294990895, 'percent_bc_gt_75'),
 (0.0072910408451984585, 'num_actv_bc_tl'),
 (0.0071780867332137226, 'num_actv_rev_tl'),
 (0.006227824047849199, 'num_bc_sats'),
 (0.006113052907867033, 'open_act_il'),
 (0.005676872686828077, 'inq_last_6mths'),
 (0.00555638979290052, 'total_cu_tl'),
 (0.004591936594888011, 'num_accts_ever_120_pd'),
 (0.00419584044642666, 'open_rv_24m'),
 (0.004184807925828211, 'tot_coll_amt'),
 (0.004115356896643273, 'home_ownership'),
 (0.004105901645065625, 'delinq_2yrs'),
 (0.004039514267889614, 'open_rv_12m'),
 (0.0035888362960960953, 'verification_status'),
 (0.0034965561503835017, 'open_il_12m'),
 (0.0034775362786705673, 'mort_acc'),
 (0.0020622122691415974, 'pub_rec_bankruptcies'),
 (0.0014670253887665847, 'application_type'),
 (0.00119142437927072, 'pub_rec'),
 (0.001045747862052861, 'initial_list_status'),
 (0.0006238230354786578, 'num_tl_90g_dpd_24m'),
 (3.8434165699261805e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag'),
 (0.0, 'collections_12_mths_ex_med'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [19]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier
eec = EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=1,
            random_state=1, replacement=False, sampling_strategy='auto',
            verbose=0, warm_start=False)
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, n_jobs=1, random_state=1)

In [20]:
 y_pred = eec.predict(X_test)

In [21]:
# Calculated the balanced accuracy score

print("Balanced Accuracy Score :",balanced_accuracy_score(y_test, y_pred))

Balanced Accuracy Score : 0.7402347548833461

In [22]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0        13129         3975
Actual 1           29           72

In [23]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))
#    "low_risk": 0,
#    "high_risk":1

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      0.77      0.71      0.87      0.74      0.55     17104
          1       0.02      0.71      0.77      0.03      0.74      0.54       101

avg / total       0.99      0.77      0.71      0.86      0.74      0.55     17205